[slizzy]
duration-tolerance = 5
min-bitrate = 315
size-factor = 2.3
size-tolerance = 0.3
id-clean = [
	' ?\[slider\.kz\]',
	' ?\(Original Mix\)',
	' ?\[TraxCrate\.com\]',
	' ?\[www\.jkmk\.net\]',
	' ?DANCEDJ\.CLUB',
	'\.mp3$',
	'\.wav$',
]

[google]
key = <key>

[beatport]
custom-search = <cs>
sim-threshold = 70

[bandcamp]
custom-search = <cs>
sim-threshold = 70

[slider]
sim-threshold = 60

[music2k]
sim-threshold = 60

[zippyshare]
custom-search = <cs>
sim-threshold = 60
blacklist = [
	'\[ClapCrate\.\w+\]',
	'\[RIP\]',
	'Bass *Boosted',
]
